### ISSUE TITLE
Kubernetes cluster's don't seem to get deleted

### ISSUE THREAD

**Issue by antevens** [crossplane-contrib/provider-digitalocean#55] opened 2022-04-06 14:29 UTC
It seems like deletion requests for Kubernetes clusters aren't successfully handled but the provider reports them as being issued successfully. After manually deleting the cluster the dokubernetescluster eventually syncs up. (Unless it takes about an hour to delete a cluster and timing just worked out this way)

kubectl delete DOKubernetesCluster xcontrol
dokubernetescluster.kubernetes.do.crossplane.io "xcontrol" deleted
error: An error occurred while waiting for the object to be deleted: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

kubectl describe DOKubernetesCluster xcontrol
Normal   DeletedExternalResource       59s (x22 over 51m)  managed/dokubernetescluster  Successfully requested deletion of external resource

- Manual deletion

kubectl delete DOKubernetesCluster xcontrol
dokubernetescluster.kubernetes.do.crossplane.io "xcontrol" deleted

kubectl describe DOKubernetesCluster xcontrol
Error from server (NotFound): dokubernetesclusters.kubernetes.do.crossplane.io "xcontrol" not found

**Comment by ADustyOldMuffin** [comment] 2022-04-06 14:37
Hello, this seems to be a dupe of #45 I'm going to close this in favor of that one since we know the issue and have a PR for a fix.

**Closed by ADustyOldMuffin** 2022-04-06 14:37 UTC
Labels: bug
